<!ELEMENT User (id, email, role, full_name)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT full_name (#PCDATA)>

<!ELEMENT City (id, name, crossroad_numbers)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT crossroad_numbers (#PCDATA)>

<!ELEMENT RoadSegment (id, city_id, start_coord, end_coord, length, quality_factor, user_intensity)>
<!ELEMENT city_id (#PCDATA)>
<!ELEMENT start_coord (#PCDATA)>
<!ELEMENT end_coord (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT quality_factor (#PCDATA)>
<!ELEMENT user_intensity (#PCDATA)>

<!ELEMENT Crossroad (id, city_id, coord, type)>
<!ELEMENT coord (#PCDATA)>
<!ELEMENT type (#PCDATA)>

<!ELEMENT CrossroadLink (crossroad_id, road_segment_id, road_degree)>
<!ELEMENT crossroad_id (#PCDATA)>
<!ELEMENT road_segment_id (#PCDATA)>
<!ELEMENT road_degree (#PCDATA)>

<!ELEMENT RoadItem (id, item_type, coord, weight, actuality)>
<!ELEMENT item_type (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT actuality (#PCDATA)>

<!ELEMENT RoadItemLink (road_item_id, road_segment_id, factor_number)>
<!ELEMENT road_item_id (#PCDATA)>
<!ELEMENT factor_number (#PCDATA)>

<!ELEMENT Request (id, user_id, start_point, end_point, datetime, preference_parameter)>
<!ELEMENT start_point (#PCDATA)>
<!ELEMENT end_point (#PCDATA)>
<!ELEMENT datetime (#PCDATA)>
<!ELEMENT preference_parameter (#PCDATA)>

<!ELEMENT Route (id, request_id, total_distance, time, total_weight)>
<!ELEMENT total_distance (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT total_weight (#PCDATA)>

<!ELEMENT Video (id, user_id, cloud_link, timelapses_json)>
<!ELEMENT cloud_link (#PCDATA)>
<!ELEMENT timelapses_json (#PCDATA)>

<!ELEMENT ImageTimeframe (id, video_id, cloud_link, coord, reliability_factor)>
<!ELEMENT reliability_factor (#PCDATA)>

<!ELEMENT RouteRoadSegmentLink (route_id, road_segment_id, sequence_number, start_coord, end_coord, total_distance, total_time)>
<!ELEMENT sequence_number (#PCDATA)>
<!ELEMENT total_time (#PCDATA)>
